/// Default commands that route to the container.
const CONTAINER_COMMANDS: &[&str] = &[
    "npm", "npx", "pnpm", "node", "python", "python3", "pip", "pip3", "curl", "make",
];

/// Where a command should execute.
#[derive(Debug, Clone, PartialEq)]
pub enum RouteTarget {
    Container,
    Host,
}

/// Classify a command as host or container.
///
/// Default rules from SPEC.md:
/// - npm/pnpm/node/python/curl etc → container
/// - Everything else → host
pub fn classify(command: &str) -> RouteTarget {
    // Extract the base command name (strip path prefix)
    let base = command.rsplit('/').next().unwrap_or(command);

    if CONTAINER_COMMANDS.contains(&base) {
        RouteTarget::Container
    } else {
        RouteTarget::Host
    }
}

/// Generate shell RC content that intercepts runtime commands for a workspace.
///
/// The generated content defines shell functions that wrap `docker exec`
/// for each command that should route to the container. These functions
/// handle TTY detection automatically.
///
/// # Arguments
/// * `container_name` - The Docker container name (e.g. "dual-lightfast-main")
/// * `extra_commands` - Additional commands to route to the container
pub fn generate_rc(container_name: &str, extra_commands: &[String]) -> String {
    let mut rc = String::new();

    rc.push_str("# Generated by dual — do not edit\n");
    rc.push_str(&format!(
        "# Shell interceptors for container: {container_name}\n\n"
    ));

    // Set the container name as an environment variable for reference
    rc.push_str(&format!("export DUAL_CONTAINER=\"{container_name}\"\n\n"));

    // Generate a function for each default container command
    for cmd in CONTAINER_COMMANDS {
        rc.push_str(&generate_function(cmd, container_name));
        rc.push('\n');
    }

    // Generate a function for each extra command
    for cmd in extra_commands {
        if !CONTAINER_COMMANDS.contains(&cmd.as_str()) {
            rc.push_str(&generate_function(cmd, container_name));
            rc.push('\n');
        }
    }

    rc
}

/// Generate a single shell function that intercepts a command.
///
/// The function:
/// - Detects if stdout is a TTY and passes -t to docker exec if so
/// - Forwards all arguments to the command inside the container
/// - Preserves exit codes
fn generate_function(command: &str, container_name: &str) -> String {
    format!(
        r#"{command}() {{
    if [ -t 1 ]; then
        command docker exec -t -w /workspace {container_name} {command} "$@"
    else
        command docker exec -w /workspace {container_name} {command} "$@"
    fi
}}
"#
    )
}

/// Generate a shell command to source the RC content from a string.
/// Useful for injecting into tmux pane creation.
pub fn source_command(container_name: &str) -> String {
    format!("eval \"$(dual shell-rc {container_name})\"")
}

/// Write the shell RC to a file and return the path.
/// RC files are written to ~/.dual/rc/{container_name}.sh
pub fn write_rc_file(
    container_name: &str,
    extra_commands: &[String],
) -> Result<std::path::PathBuf, std::io::Error> {
    let rc_dir = dirs::home_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join(".dual")
        .join("rc");
    std::fs::create_dir_all(&rc_dir)?;

    let rc_path = rc_dir.join(format!("{container_name}.sh"));
    let rc_content = generate_rc(container_name, extra_commands);
    std::fs::write(&rc_path, rc_content)?;

    Ok(rc_path)
}

/// Marker comment used to detect if the snippet is already installed.
const RC_MARKER: &str = "# dual: shell interception (auto-generated)";

/// Generate the shell RC snippet that auto-sources Dual interception.
///
/// This snippet is appended to ~/.bashrc or ~/.zshrc. It detects
/// the DUAL_ACTIVE env var (set by tmux set-environment) and sources
/// the workspace-specific RC file.
pub fn shell_hook_snippet() -> String {
    format!(
        r#"
{RC_MARKER}
if [ -n "$DUAL_ACTIVE" ] && [ -n "$DUAL_RC_PATH" ] && [ -f "$DUAL_RC_PATH" ]; then
    source "$DUAL_RC_PATH"
fi
"#
    )
}

/// Detect the user's shell RC file path.
///
/// Returns the path to ~/.zshrc or ~/.bashrc based on $SHELL.
/// Returns None if the shell is not bash or zsh.
pub fn detect_shell_rc() -> Option<std::path::PathBuf> {
    let home = dirs::home_dir()?;
    let shell = std::env::var("SHELL").unwrap_or_default();
    let base = shell.rsplit('/').next().unwrap_or("");

    match base {
        "zsh" => Some(home.join(".zshrc")),
        "bash" => Some(home.join(".bashrc")),
        _ => None,
    }
}

/// Install the auto-source snippet into the user's shell RC file.
///
/// Idempotent: checks for the marker comment before appending.
/// Creates the RC file if it doesn't exist.
/// Returns Ok(true) if the snippet was newly installed, Ok(false) if
/// already present.
pub fn install_shell_hook() -> Result<bool, std::io::Error> {
    let rc_path = match detect_shell_rc() {
        Some(p) => p,
        None => return Ok(false),
    };

    // Read existing content (or empty if file doesn't exist)
    let existing = std::fs::read_to_string(&rc_path).unwrap_or_default();

    // Check if snippet is already installed
    if existing.contains(RC_MARKER) {
        return Ok(false);
    }

    // Append snippet
    use std::io::Write;
    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&rc_path)?;
    file.write_all(shell_hook_snippet().as_bytes())?;

    Ok(true)
}

/// Get the source command for an RC file path.
pub fn source_file_command(rc_path: &std::path::Path) -> String {
    format!("source \"{}\"", rc_path.display())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classify_container_commands() {
        assert_eq!(classify("npm"), RouteTarget::Container);
        assert_eq!(classify("npx"), RouteTarget::Container);
        assert_eq!(classify("pnpm"), RouteTarget::Container);
        assert_eq!(classify("node"), RouteTarget::Container);
        assert_eq!(classify("python"), RouteTarget::Container);
        assert_eq!(classify("python3"), RouteTarget::Container);
        assert_eq!(classify("pip"), RouteTarget::Container);
        assert_eq!(classify("curl"), RouteTarget::Container);
        assert_eq!(classify("make"), RouteTarget::Container);
    }

    #[test]
    fn classify_host_commands() {
        assert_eq!(classify("git"), RouteTarget::Host);
        assert_eq!(classify("cat"), RouteTarget::Host);
        assert_eq!(classify("ls"), RouteTarget::Host);
        assert_eq!(classify("vim"), RouteTarget::Host);
        assert_eq!(classify("nvim"), RouteTarget::Host);
        assert_eq!(classify("ssh"), RouteTarget::Host);
    }

    #[test]
    fn classify_strips_path_prefix() {
        assert_eq!(classify("/usr/bin/npm"), RouteTarget::Container);
        assert_eq!(classify("/usr/local/bin/node"), RouteTarget::Container);
        assert_eq!(classify("/usr/bin/git"), RouteTarget::Host);
    }

    #[test]
    fn generate_rc_contains_functions() {
        let rc = generate_rc("dual-lightfast-main", &[]);

        // Should contain the container name export
        assert!(rc.contains("export DUAL_CONTAINER=\"dual-lightfast-main\""));

        // Should contain functions for all container commands
        assert!(rc.contains("npm()"));
        assert!(rc.contains("npx()"));
        assert!(rc.contains("pnpm()"));
        assert!(rc.contains("node()"));
        assert!(rc.contains("python()"));
        assert!(rc.contains("curl()"));
    }

    #[test]
    fn generate_rc_has_tty_detection() {
        let rc = generate_rc("dual-lightfast-main", &[]);
        assert!(rc.contains("if [ -t 1 ]; then"));
        assert!(rc.contains("docker exec -t"));
    }

    #[test]
    fn generate_rc_uses_correct_container() {
        let rc = generate_rc("dual-agent-os-feat__memory", &[]);
        assert!(rc.contains("dual-agent-os-feat__memory"));
        // Every function should reference this container
        for cmd in CONTAINER_COMMANDS {
            assert!(rc.contains(&format!(
                "command docker exec -t -w /workspace dual-agent-os-feat__memory {cmd}"
            )));
        }
    }

    #[test]
    fn generate_rc_with_extra_commands() {
        let extras = vec!["cargo".to_string(), "go".to_string()];
        let rc = generate_rc("dual-test", &extras);
        assert!(rc.contains("cargo()"));
        assert!(rc.contains("go()"));
        // Default commands should still be present
        assert!(rc.contains("npm()"));
    }

    #[test]
    fn generate_rc_extra_commands_no_duplicates() {
        // If an extra command matches a default, it should not be duplicated
        let extras = vec!["npm".to_string(), "cargo".to_string()];
        let rc = generate_rc("dual-test", &extras);
        // Count "\nnpm() {" to avoid matching "pnpm() {" substring
        let npm_count = rc.matches("\nnpm() {").count();
        assert_eq!(npm_count, 1);
        assert!(rc.contains("cargo()"));
    }

    #[test]
    fn generated_function_preserves_args() {
        let func = generate_function("npm", "dual-test");
        assert!(func.contains("\"$@\""));
    }

    #[test]
    fn source_command_format() {
        let cmd = source_command("dual-lightfast-main");
        assert_eq!(cmd, "eval \"$(dual shell-rc dual-lightfast-main)\"");
    }

    #[test]
    fn write_rc_file_creates_file() {
        let path = write_rc_file("dual-test-write-rc", &[]).unwrap();
        assert!(path.exists());
        // Verify it's under ~/.dual/rc/
        let path_str = path.to_string_lossy();
        assert!(
            path_str.contains(".dual/rc/"),
            "RC file should be under ~/.dual/rc/, got: {path_str}"
        );
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("export DUAL_CONTAINER=\"dual-test-write-rc\""));
        assert!(content.contains("npm()"));
        // Clean up
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn source_file_command_format() {
        let path = std::path::Path::new("/home/user/.dual/rc/dual-test.sh");
        let cmd = source_file_command(path);
        assert_eq!(cmd, "source \"/home/user/.dual/rc/dual-test.sh\"");
    }

    #[test]
    fn source_file_command_handles_spaces() {
        let path =
            std::path::Path::new("/Users/user/Library/Application Support/dual/rc/dual-test.sh");
        let cmd = source_file_command(path);
        assert_eq!(
            cmd,
            "source \"/Users/user/Library/Application Support/dual/rc/dual-test.sh\""
        );
    }

    #[test]
    fn shell_hook_snippet_contains_guard() {
        let snippet = shell_hook_snippet();
        assert!(snippet.contains("DUAL_ACTIVE"));
        assert!(snippet.contains("DUAL_RC_PATH"));
        assert!(snippet.contains("source"));
        assert!(snippet.contains(RC_MARKER));
    }

    #[test]
    fn shell_hook_snippet_is_noop_without_vars() {
        let snippet = shell_hook_snippet();
        assert!(snippet.contains("-n \"$DUAL_ACTIVE\""));
        assert!(snippet.contains("-f \"$DUAL_RC_PATH\""));
    }

    #[test]
    fn detect_shell_rc_respects_shell_env() {
        let original = std::env::var("SHELL").ok();

        // SAFETY: test runs single-threaded
        unsafe {
            std::env::set_var("SHELL", "/bin/zsh");
            let path = detect_shell_rc();
            assert!(path.is_some());
            assert!(path.unwrap().ends_with(".zshrc"));

            std::env::set_var("SHELL", "/bin/bash");
            let path = detect_shell_rc();
            assert!(path.is_some());
            assert!(path.unwrap().ends_with(".bashrc"));

            std::env::set_var("SHELL", "/usr/bin/fish");
            let path = detect_shell_rc();
            assert!(path.is_none());

            // Restore
            match original {
                Some(v) => std::env::set_var("SHELL", v),
                None => std::env::remove_var("SHELL"),
            }
        }
    }

    #[test]
    fn install_shell_hook_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let rc_path = dir.path().join(".zshrc");
        std::fs::write(&rc_path, "# existing config\n").unwrap();

        // Manually write snippet to test idempotency detection
        let mut f = std::fs::OpenOptions::new()
            .append(true)
            .open(&rc_path)
            .unwrap();
        use std::io::Write;
        f.write_all(shell_hook_snippet().as_bytes()).unwrap();
        drop(f);

        let content = std::fs::read_to_string(&rc_path).unwrap();
        let marker_count = content.matches(RC_MARKER).count();
        assert_eq!(marker_count, 1);
    }
}
